@startuml "precedent_acceptor_from_gadgets"

!theme toy

actor User 

User -> AcceptorFromGadgets : connect
User -> AcceptorFromGadgets : send name and room id
create ParticipantFromGadgets
AcceptorFromGadgets -> ParticipantFromGadgets : make connection
AcceptorFromGadgets -> ParticipantFromGadgets : attach name and room id to connection

loop is user connected
    ParticipantFromGadgets -> ParticipantFromGadgets : *handle*
end

AcceptorFromGadgets -> AcceptorFromGadgets : accept

@enduml

